[[Snippets]]
  Description = "Create a .keep file in all empty directories"
  Output = ""
  Tag = []
  command = "find . -type d -empty -print0 | xargs -0 -I % touch %/.keep"

[[Snippets]]
  Description = "Display all listen port"
  Output = ""
  Tag = []
  command = "lsof -Pan -i tcp -i udp"

[[Snippets]]
  Description = "Process with the largest memory usage"
  Output = ""
  Tag = []
  command = "ps aux | sort -nrk +4 | head -n 1"

[[Snippets]]
  Description = "Top 10 IP address with the number of occurrences"
  Output = ""
  Tag = []
  command = "tail -10000 access_log | cut -f 1 -d ' ' | sort | uniq -c | sort -nr | head -10"

[[Snippets]]
  Description = "All file rename (01.txt -> 01.md)"
  Output = ""
  Tag = []
  command = "ls | sed -e s/\\.txt// | awk '{print  .txt   .md}' | xargs -n 2 mv"

[[Snippets]]
  Description = "Descending order of line length"
  Output = ""
  Tag = []
  command = "awk '{print length($0), $0}' sample.txt | sort -nr | head"

[[Snippets]]
  Description = "Check expiration date of SSL certficate"
  Output = ""
  Tag = []
  command = "echo | openssl s_client -connect example.com:443 2> /dev/null | openssl x509 -dates -noout"

[[Snippets]]
  Description = "Get my global IP address"
  Output = ""
  Tag = []
  command = "curl ifconfig.co"

[[Snippets]]
  Description = "terraform fmt"
  Output = ""
  Tag = []
  command = "terraform fmt -recursive ."

[[Snippets]]
  Description = "ecr docker login"
  Output = ""
  Tag = []
  command = "aws ecr get-login-password | docker login --username AWS --password-stdin $(aws sts get-caller-identity --query Account --output text).dkr.ecr.$(aws configure get region --profile=$AWS_PROFILE).amazonaws.com"

[[Snippets]]
  Description = "Get Hashicorp vault secrets using cURL"
  Output = ""
  Tag = ["vault", "secret"]
  command = "curl -s -X GET -H \"X-Vault-Token:<VAULT_TOKEN=$VAULT_TOKEN>\" <VAULT_ADDR=$VAULT_ADDR>/v1/<ENGINE>/data/<SECRET_PATH> | jq ."

[[Snippets]]
  Description = "Flush OSX Mac DNS Cache"
  Output = ""
  Tag = []
  command = "sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder"

[[Snippets]]
  Description = "git remote rebase"
  Output = ""
  Tag = []
  command = "git fetch --all --prune --prune-tags && git rebase"

[[Snippets]]
  Description = "Mount RAMDisk (Default 5Gb)"
  Output = ""
  Tag = []
  command = "diskutil erasevolume HFS+ \"RAMDisk\" `hdiutil attach -nomount ram://<size=10485760>`"

[[Snippets]]
  Description = "Decode JWT"
  Output = ""
  Tag = []
  command = "jq -R 'split(\".\") | select(length > 0) | .[0],.[1] | @base64d | fromjson' <<< $JWT"

[[Snippets]]
  Description = "Git: Search Recursively"
  Output = ""
  Tag = []
  command = "git log --branches -i --all -p -S \"<SEARCH_REGEX=$SEARCH_REGEX>\""

[[Snippets]]
  Description = "Git: Get branch containing commit"
  Output = ""
  Tag = []
  command = "git branch -a --contains \"<COMMIT_SHA=$COMMIT_SHA>\""

[[Snippets]]
  Description = "Kubernetes: Clear context"
  Output = ""
  Tag = []
  command = "kubectl config unset current-context"

[[Snippets]]
  Description = "Postgres: Find long running query"
  Output = ""
  Tag = []
  command = "echo \"SELECT pid,  now() - pg_stat_activity.query_start AS duration, query, state FROM pg_stat_activity WHERE (now() - pg_stat_activity.query_start) > interval '5 minutes';\""

[[Snippets]]
  Description = "Remove ALL local branches that are not on remote"
  Output = ""
  Tag = []
  command = "git fetch -p && git branch -vv | grep ': gone]' | awk '{print $1}' | xargs git branch -D"

[[Snippets]]
  Description = "Check if remote port is open via Bash"
  Output = ""
  Tag = []
  command = "timeout 5 bash -c ': < /dev/tcp/google.com/80' && echo OK || echo ERROR"

[[Snippets]]
  Description = "Check if remote port is open via Netcat. Use -u for UDP or -t for TCP"
  Output = ""
  Tag = []
  command = "nc -vztw5 google.com 80"

[[Snippets]]
  Description = "List all kubernetes secrets in namespace base64decoded and json output"
  Output = ""
  Tag = []
  command = "kubectl get secrets -o json | jq '.items[] | {name: .metadata.name,data: .data|map_values(@base64d)}'"

[[Snippets]]
  Description = "Generate Vault Token with extended TTL"
  Output = ""
  Tag = ["vault", "token"]
  command = "vault token create -ttl <TTL=12h> <policy=-orphan -no-default-policy -policy=admin> -display-name=$HOSTNAME -explicit-max-ttl=<TTL=12h> -metadata=created-for=$HOSTNAME -field=token"

[[Snippets]]
  Description = "Remove the quarantine attribute from the Application. Ref: https://librewolf.net/docs/faq/#why-is-librewolf-marked-as-broken"
  Output = ""
  Tag = []
  command = "xattr -dr com.apple.quarantine /Applications/<App=LibreWolf>.app"
